### ISSUE TITLE
[Doc Error]: False Statement

### ISSUE THREAD

**Issue by laurentbouquin** [algosup/2024-2025-project-2-serious-game-team-7#6]
### Which document is concerned?

Technical_Specifications.md

### What is the error?

In the 2.1 part, It says that we only target MacOs as We are developing the game on MacOs, but as Godot allows for export in Windows, MacOs and Linux, we should at least target Windows and MacOs.

This has to be redefined by discussing with the team.

### priority

Urgent

**Comment by PaulNowak36** [comment]
done
