### ISSUE TITLE
[Doc Error]: Wrong File Format

### ISSUE THREAD

**Issue by laurentbouquin** [algosup/2024-2025-project-2-serious-game-team-7#9]
### Which document is concerned?

Technical_Specifications.md

### What is the error?

In the 3.2 part, a file is named "DataLoader.gd" but as we are doing the game in C#, the name of the file should be "DataLoader.cs".

Also, In the whole document, some file names are in the ".gd" format but should end with ".cs" instead.

### priority

Should be done quickly

**Comment by PaulNowak36** [comment]
fixed
